### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Alvazz** [scchn/CamPrefs#4]
MacOS: 10.15.7
XCode: Version 12.4 (12D4e)

When I started to compile, I encountered these errors.
<img width="801" alt="error1" src="https://user-images.githubusercontent.com/50744096/131951658-61d6cfd7-b189-47df-b486-45f33504965b.png">

**Comment by scchn** [comment]
I'm using _macOS 11.5.2_ and _macOS 12 beta_ and there's no error.
I guess it might be the system SDK change.
You can download the notarized app in the release page below.
Sorry for the inconvenience.

https://github.com/scchn/CamPrefs/releases/tag/v1.0.0

**Comment by Alvazz** [comment]
Thank you for your reply, I followed the URL you provided to download, but it seems that I can’t find the device?
<img width="145" alt="error2" src="https://user-images.githubusercontent.com/50744096/131958652-7f061e44-099a-415b-bc7c-41470721d309.png">

**Comment by scchn** [comment]
What kind of camera do you use? USB webcam or FaceTime camera?

**Comment by Alvazz** [comment]
Actually I just started Cam Prefs.app, I didn’t perform any other operations, I don’t know what I should do next, and I don’t seem to see any GUI.

**Comment by Alvazz** [comment]
In addition, I am using a MacBook Pro, and the computer comes with a camera. In addition, I also connected a USB Webcam through the UBS connection slot.

**Comment by scchn** [comment]
Cam Pres is aim at customize UVC controls for USB cameras.

It seems that there are problems that I was unable to fix for now.
(mostly unable to open underlaying device)

You can try my app on the Mac App Store called [XCap](https://apps.apple.com/app/xcap/id1569525013?mt=12), but there's no guarantee that it will work as expected too.
I just changed its price from paid to free, it may take a while to see the change.

**Comment by Alvazz** [comment]
OK, i will try and give feedback later. thanks

**Comment by Alvazz** [comment]
Hi dude.
It seems to work, and advanced features seem to be able to support it. So, what is the difference between the two, and what I just want to use is the function of webcam setting. Or whether it is possible to separate the webcam setting module.

**Comment by scchn** [comment]
Can you build the latest commit and see if there's any error?

**Comment by scchn** [comment]
Can you build the latest commit and see if there are any errors?

**Comment by Alvazz** [comment]
It looks like it can work. If I find any problems, I will give you feedback and praise your great work. Coooool...
